/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_gestion (void);
GtkWidget* create_menu (void);
GtkWidget* create_test (void);
GtkWidget* create_gestion_calendrier (void);
GtkWidget* create_gestionDesCapteurs (void);
GtkWidget* create_gestion_equipement (void);
GtkWidget* create_acceuil_gestion_equipement (void);
GtkWidget* create_authentification (void);
GtkWidget* create_gestion_troupeaux (void);
GtkWidget* create_espace_troupeaux (void);
GtkWidget* create_Acceuil_client (void);
GtkWidget* create_Gestion_client (void);
GtkWidget* create_creation_compte_admin (void);
GtkWidget* create_surface_admin (void);
GtkWidget* create_dashbord (void);
GtkWidget* create_meilleur_ouvrier (void);
GtkWidget* create_nombre_de_troupeaux (void);
GtkWidget* create_anneeseche (void);
GtkWidget* create_taux_absenteisme (void);
GtkWidget* create_creation_compte_employer (void);
GtkWidget* create_capdef (void);
GtkWidget* create_window_capteur_valeur_alarmante (void);
